Vagrant.configure("2") do |config|
    config.vm.define "dmz" do |dmz|
      dmz.vm.box = "debian/buster64"
      dmz.vm.hostname = "dmz"
      dmz.vm.network "private_network", ip: "192.168.56.254", virtualbox__intnet: "net_interne_56", device: "eth1"
      dmz.vm.network "private_network", ip: "192.168.57.254", virtualbox__intnet: "net_interne_57", device: "eth2"

      dmz.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      dmz.vm.provision "file", source: "test.sh", destination: "/tmp/test.sh"
      dmz.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.58.0/24 via 192.168.56.200
        chmod +x /tmp/test.sh
        sudo apt install -y ufw
        sudo ufw enable
        sudo systemctl start ufw
        echo 1 > /proc/sys/net/ipv4/ip_forward
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p
      SHELL
      dmz.vm.provision "shell", path: "set-up-ufw-dmz.sh"
    end
  end
  