Vagrant.configure("2") do |config|
    # Configuration de la VM DMZ
    config.vm.define "dmz" do |dmz|
      dmz.vm.box = "debian/buster64"
      dmz.vm.hostname = "dmz"
      dmz.vm.network "private_network", ip: "192.168.56.254", device: "eth1"
      dmz.vm.network "private_network", ip: "192.168.57.254", device: "eth2"
      dmz.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  # 1 Go de RAM pour la VM serveur
      end
      config.vm.provision "shell", path: "set-up_iptables.sh"
      dmz.vm.provision "shell", inline: <<-SHELL
        # Activer le routage IP
        echo 1 > /proc/sys/net/ipv4/ip_forward
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        sysctl -p
      SHELL
    end
  end
  