Vagrant.configure("2") do |config|
    config.vm.define "router" do |router|
     router.vm.box = "debian/buster64"
     router.vm.hostname = "router"
     router.vm.network "private_network", ip: "192.168.56.200", virtualbox__intnet: "net_interne_56", device: "eth1"
     router.vm.network "private_network", ip: "192.168.58.200", virtualbox__intnet: "net_interne_58", device: "eth2"
    router.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
     end 
     router.vm.provision "file", source: "test.sh", destination: "/tmp/test.sh"
     router.vm.provision "shell", inline: <<-SHELL
       chmod +x /tmp/test.sh
       sudo ip route add 192.168.57.0/24 via 192.168.56.254
       echo 1 > /proc/sys/net/ipv4/ip_forward
       echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
       sysctl -p
     SHELL
   end
 end
 