Vagrant.configure("2") do |config|
   config.vm.define "client" do |client|
    client.vm.box = "debian/buster64"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.200", virtualbox__intnet: "net_interne_56", device: "eth1"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end 
    client.vm.provision "shell", inline: <<-SHELL
      sudo ip route add 192.168.57.0/24 via 192.168.56.254
      apt-get update && apt-get upgrade -y
      apt-get install -y curl nmap
    SHELL
  end
end
