Vagrant.configure("2") do |config|
   # Configuration de la VM test
   config.vm.define "test" do |test|
    test.vm.box = "debian/buster64"
    test.vm.hostname = "test"
    test.vm.network "private_network", ip: "192.168.56.200"
    test.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # 1 Go de RAM pour la VM test
    end
    test.vm.provision "shell", inline: <<-SHELL
      # Mise à jour des paquets
      apt-get update && apt-get upgrade -y
      # Installation de curl et nmap pour tester l'accès web et la sécurité
      apt-get install -y curl nmap
      # Test de l'accès à la page web du serveur
      #curl http://192.168.50.4/
      # Scanner les ports ouverts du serveur pour vérifier la sécurité
      #nmap 192.168.50.4
    SHELL
  end
end
