Vagrant.configure("2") do |config|
   # Configuration de la VM client
   config.vm.define "client" do |client|
    client.vm.box = "debian/buster64"
    client.vm.hostname = "client"
    #client.vm.network "private_network", ip: "192.168.56.200"
    client.vm.network "private_network", ip: "192.168.56.200", virtualbox__intnet: "net_interne_56", device: "eth1"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # 1 Go de RAM pour la VM client
    end 
    client.vm.provision "shell", inline: <<-SHELL
      sudo ip route add 192.168.57.0/24 via 192.168.56.254
      # Mise à jour des paquets
      apt-get update && apt-get upgrade -y
      # Installation de curl et nmap pour tester l'accès web et la sécurité
      apt-get install -y curl nmap
    SHELL
  end
end
