Vagrant.configure("2") do |config|
    # Configuration de la VM serveur
    config.vm.define "server" do |server|
      server.vm.box = "debian/buster64"
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.56.4"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  # 1 Go de RAM pour la VM serveur
      end
      server.vm.provision "shell", inline: <<-SHELL
        # Mise à jour des paquets
        apt-get update && apt-get upgrade -y
        # Installation de Nginx
        apt-get install -y nginx
        # Installation de ufw (pare-feu)
        apt-get install -y ufw
        # Configuration de ufw (activation et configuration de base)
        ufw allow 'Nginx HTTP'
        ufw enable
        ufw status
        # Création d'une page HTML simple
        echo '<html><body><h1>Page Statique Nginx</h1></body></html>' > /var/www/html/index.html
        # Redémarrer nginx pour s'assurer qu'il sert la page
        systemctl restart nginx
      SHELL
    end
end