Vagrant.configure("2") do |config|
    config.vm.define "server" do |server|
      server.vm.box = "debian/buster64"
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.56.100", virtualbox__intnet: "net_interne_56", device: "eth1"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      server.vm.provision "file", source: "../../scripts/manage-firewall.sh", destination: "/tmp/manage-firewall.sh"
      server.vm.provision "file", source: "avail.txt", destination: "/tmp/avail.txt"
      server.vm.provision "file", source: "nginxconf.txt", destination: "/tmp/nginxconf.txt"
      server.vm.provision "file", source: "index.html", destination: "/tmp/index.html"
      server.vm.provision "file", source: "test.sh", destination: "/tmp/test.sh"
      server.vm.provision "shell", inline: <<-SHELL
        chmod +x /tmp/test.sh
        sudo ip route add 192.168.57.0/24 via 192.168.56.254
        sudo ip route add 192.168.58.0/24 via 192.168.56.200
        apt-get update && apt-get upgrade -y
        apt-get install -y nginx ufw
        chmod +x /tmp/manage-firewall.sh
        cp /tmp/index.html /var/www/html/index.html
        sudo cp /tmp/avail.txt /etc/nginx/sites-available/default
        sudo cp /tmp/nginxconf.txt /etc/nginx/nginx.conf
        systemctl restart nginx
      SHELL
    end
end