Vagrant.configure("2") do |config|
    # Configuration de la VM serveur
    config.vm.define "server" do |server|
      server.vm.box = "debian/buster64"
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.56.100"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  # 1 Go de RAM pour la VM serveur
      end
      server.vm.provision "file", source: "../../scripts/manage-firewall.sh", destination: "/tmp/manage-firewall.sh"
      server.vm.provision "file", source: "index.html", destination: "/tmp/index.html"
      server.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.57.0/24 via 192.168.56.254
        # Mise à jour des paquets
        apt-get update && apt-get upgrade -y
        # Installation de Nginx, ufw
        apt-get install -y nginx ufw
        # Configuration de ufw (activation et configuration de base)
        #ufw allow 80
        sudo ufw enable
        sudo ufw status
        chmod +x /tmp/manage-firewall.sh
        # application index
        cp /tmp/index.html /var/www/html/index.html
        #echo '<html><body><h1>Page Statique Nginx</h1></body></html>' > /var/www/html/index.html
        # Redémarrer nginx pour s'assurer qu'il sert la page
        systemctl restart nginx
      SHELL
    end
end