Vagrant.configure("2") do |config|
    config.vm.define "internet" do |internet|
      internet.vm.box = "debian/buster64"
      internet.vm.hostname = "internet"
      internet.vm.network "private_network", ip: "192.168.57.1", virtualbox__intnet: "net_interne_57", device: "eth1"
      internet.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      internet.vm.provision "file", source: "DDOS.sh", destination: "/tmp/ddos.sh"
      internet.vm.provision "file", source: "test.sh", destination: "/tmp/test.sh"
      internet.vm.provision "shell", inline: <<-SHELL
        sudo apt install apache2-utils -y
        chmod +x /tmp/ddos.sh /tmp/test.sh
        sudo ip route add 192.168.56.0/24 via 192.168.57.254
        sudo ip route add 192.168.58.0/24 via 192.168.57.254
        apt-get update && apt-get upgrade -y
        apt-get install -y curl nmap
    SHELL
  end
end