Vagrant.configure("2") do |config|
    config.vm.define "internet" do |internet|
      internet.vm.box = "debian/buster64"
      internet.vm.hostname = "internet"
      internet.vm.network "private_network", ip: "192.168.57.1", virtualbox__intnet: "net_interne_57", device: "eth1"
      internet.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      internet.vm.provision "shell", inline: <<-SHELL
        sudo ip route add 192.168.56.0/24 via 192.168.57.254
    SHELL
  end
end