Vagrant.configure("2") do |config|
    # Configuration de la VM serveur
    config.vm.define "internet" do |internet|
      internet.vm.box = "debian/buster64"
      internet.vm.hostname = "internet"
      #internet.vm.network "private_network", ip: "192.168.57.100"
      #internet.vm.network "private_network", ip: "192.168.57.1"
      internet.vm.network "private_network", ip: "192.168.57.1", virtualbox__intnet: "net_interne_57"
      internet.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  # 1 Go de RAM pour la VM serveur
      end
      internet.vm.provision "shell", inline: <<-SHELL
        # Mise à jour des routes
        sudo ip route add 192.168.56.0/24 via 192.168.57.254
    SHELL
  end
end